version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    ports:
      - 8082:8080
    depends_on:
      - "db"
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: testgo_development
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./user.sql:/docker-entrypoint-initdb.d/init.sql
      # - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      # ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'root';
    ports:
      - 13306:3306

# volumes:
#   db-data: